### ISSUE TITLE
Bug: When AWS_LWA_INVOKE_MODE: response_streaming with empty body, LWA fails to send termination chunk

### ISSUE THREAD

**Issue by bestickley** [awslabs/aws-lambda-web-adapter#499]
First, thank you for such an amazing tool!

I'm running Next.js in Lambda with Lambda Web Adapter via Function URL behind CloudFront with AWS_LWA_INVOKE_MODE: response_streaming. I'm using [Authjs/NextAuth](https://authjs.dev/) to redirect users to Cognito to authenticate and then Cognito redirects the user back to my Next.js app to /api/auth/callback/cognito?code=123abc where NextAuth picks up the request and then sends a redirect (302) back to client to redirect user to the app's home page. Currently, CloudFront is timing out the request (default 30 sec) which makes for poor UX. I've worked with AWS Support because at first I thought this was a CloudFront issue. But the CloudFront Support team has told me it's not an issue with CloudFront but an issue with the lambda since the request has Transfer-Encoding: chunked but it's not sending the correct termination chunk. When NextAuth sends the redirect it has a body size of 0. When I force the body size to be > 0 then the request succeeds which is my current work around. So I think there is a bug in LWA that when there is a body size of 0 it fails to send the termination chunk which should look like:
```
0\r\n
\r\n
```
see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#chunked_encoding

I have more information to share if needed based on CloudFront Support team's analysis that I can share privately.

**Comment by bnusunny** [comment]
Thanks for reporting this issue. 

I'm not so sure this is the root cause of your issue. In the [FastAPI Response Streaming](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-response-streaming) example, the app's root path redirect to "/demo" with 0 length body, and it works perfectly with CloudFront. You could deploy that example and put a CloudFront distribution in front of it to verify.

**Comment by gfmsb** [comment]
Hi Team. I've helped @bestickley through the troubleshooting, and the issue is not happening all the time. The exact same type of requests sometimes goes through immediately, and other times takes as long as the origin read timeout set on CloudFront. When we look into the logs, we observe that CF sends the request to Lambda Function URL and Lambda responds very fast. CloudFront receives all the headers of the response very fast in all circumstances. However,  for requests that eventually timeout, there is a 0 size body, while for the requests that don't timeout there is a very small body size. As CloudFront makes the request to Lambda Function URL using HTTP1.1 and the response is coming with response header `Transfer-Encoding=chunked`, there should be always size body different than zero to accommodate the termination chunk sequence. Our understanding is that the timeout is happening because that sequence is not received by CloudFront in some situations. Again, it is not happening all the time so @bestickley configuration might be hitting some edge case triggering this behaviour. Please reachout to me where i can share specific details on how these was troubleshooted.

**Comment by bnusunny** [comment]
@gfmsb  Thanks for the details. Reaching out you for more details.

**Comment by bnusunny** [comment]
We confirmed this is not a bug with Lambda Web Adapter.
